'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CORE_artist
    Public Property idMN As String
    Public Property nameMN As String
    Public Property urlSource As String
    Public Property ranking As Integer
    Public Property urlImage As String
    Public Property biographpy As String
    Public Property beginDate As Nullable(Of Date)
    Public Property genre As String
    Public Property lastUpdated As Nullable(Of Date)
    Public Property idArtistDZ As Nullable(Of Integer)
    Public Property widthImage As Nullable(Of Integer)
    Public Property heightImage As Nullable(Of Integer)

    Public Overridable Property mc_composition As ICollection(Of mc_composition) = New HashSet(Of mc_composition)

End Class
