'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mc_composition
    Public Property idWork As String
    Public Property nameWork As String
    Public Property idComposerMN As String
    Public Property composedDate As String
    Public Property urlSource As String
    Public Property workGenre As String
    Public Property workType As String
    Public Property description As String
    Public Property descriptionAuthor As String
    Public Property featured As String
    Public Property performancesCount As Nullable(Of Integer)
    Public Property atAgeOf As String
    Public Property lastProcesed As Nullable(Of Date)

    Public Overridable Property CORE_artist As CORE_artist

End Class
