'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mn_composer_rel
    Public Property idComposer As String
    Public Property idRelTip As Integer
    Public Property idComposerRel As String
    Public Property nOrd As Integer

    Public Overridable Property mn_composer As mn_composer
    Public Overridable Property mn_relTip As mn_relTip

End Class
