'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class masterEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=masterEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CORE_artist() As DbSet(Of CORE_artist)
    Public Overridable Property mc_composition() As DbSet(Of mc_composition)
    Public Overridable Property mc_composition_parts() As DbSet(Of mc_composition_parts)
    Public Overridable Property mn_composer() As DbSet(Of mn_composer)
    Public Overridable Property mn_composer_rel() As DbSet(Of mn_composer_rel)
    Public Overridable Property mn_relTip() As DbSet(Of mn_relTip)
    Public Overridable Property MSreplication_options() As DbSet(Of MSreplication_options)
    Public Overridable Property spt_fallback_db() As DbSet(Of spt_fallback_db)
    Public Overridable Property spt_fallback_dev() As DbSet(Of spt_fallback_dev)
    Public Overridable Property spt_fallback_usg() As DbSet(Of spt_fallback_usg)
    Public Overridable Property spt_monitor() As DbSet(Of spt_monitor)
    Public Overridable Property spt_values() As DbSet(Of spt_values)

End Class
