'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MSreplication_options
    Public Property optname As String
    Public Property value As Boolean
    Public Property major_version As Integer
    Public Property minor_version As Integer
    Public Property revision As Integer
    Public Property install_failures As Integer

End Class
