'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spt_values
    Public Property name As String
    Public Property number As Integer
    Public Property type As String
    Public Property low As Nullable(Of Integer)
    Public Property high As Nullable(Of Integer)
    Public Property status As Nullable(Of Integer)

End Class
