'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spt_fallback_dev
    Public Property xserver_name As String
    Public Property xdttm_ins As Date
    Public Property xdttm_last_ins_upd As Date
    Public Property xfallback_low As Nullable(Of Integer)
    Public Property xfallback_drive As String
    Public Property low As Integer
    Public Property high As Integer
    Public Property status As Short
    Public Property name As String
    Public Property phyname As String

End Class
