'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spt_fallback_usg
    Public Property xserver_name As String
    Public Property xdttm_ins As Date
    Public Property xdttm_last_ins_upd As Date
    Public Property xfallback_vstart As Nullable(Of Integer)
    Public Property dbid As Short
    Public Property segmap As Integer
    Public Property lstart As Integer
    Public Property sizepg As Integer
    Public Property vstart As Integer

End Class
